# Generated by Django 6.1 on 2026-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(help_text='В ГБ'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.IntegerField(help_text='В ГБ'),
        ),
    ]
